version: '3.8'

services:
  # Node.js backend service
  backend:
    build:
      context: ./server # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile # Name of your Dockerfile in the server folder
    ports:
      - "3001:3001"
    depends_on:
      - db # Ensures the database starts first
      - redis # Ensures Redis starts before the backend
    environment:
      - DB_HOST=db # Points to the db container (service name)
      - DB_USER=root
      - DB_PASSWORD=Polaci2021. # Set a password for MySQL
      - DB_NAME=qerdhja # Specify the database name
      - REDIS_HOST=redis # Points to the Redis container (service name)
      - REDIS_PORT=6379 # Default Redis port

  # React frontend service
  frontend:
    build: ./client # Path to the frontend directory (where your Dockerfile is)
    ports:
      - "3000:3000" # Exposes port 3000 for the frontend

  # MySQL database service
  db:
    image: mysql:8.0 # Use the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: Polaci2021. # Set root password for MySQL
      MYSQL_DATABASE: qerdhja # Automatically create the database
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for MySQL data

  # Redis service
  redis:
    image: redis:latest # Use the official Redis image
    container_name: redis
    ports:
      - "6379:6379" # Expose Redis port
    restart: always # Ensure Redis always restarts on failure

volumes:
  mysql_data: # Docker volume to store MySQL data
