name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js for client
      - name: Set up Node.js for client
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install client dependencies
      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      # Run client tests
      - name: Run client tests
        working-directory: ./client
        run: npm test -- --passWithNoTests

      # Build the client project (React app)
      - name: Build client project
        working-directory: ./client
        run: npm run build

      # Set up Node.js for server
      - name: Set up Node.js for server
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install server dependencies
      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      # Run server tests (if any)
      - name: Run server tests
        working-directory: ./server
        run: npm test -- --passWithNoTests

      # Build Docker Image for Server
      - name: Build Docker Image for Server
        run: docker build -f server/Dockerfile -t my-app-server:latest .

      # Build Docker Image for Client
      - name: Build Docker Image for Client
        run: docker build -f client/Dockerfile -t my-app-client:latest .

      # Docker login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Server Docker Image
      - name: Push Server Docker Image
        run: docker push my-app-server:latest

      # Push Client Docker Image
      - name: Push Client Docker Image
        run: docker push my-app-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Example for deploying to AWS EC2 instance or similar
      - name: Deploy to Server
        run: |
          echo "Deploying to production server..."
          # SSH into server and pull Docker images (update this as needed)
          docker pull my-app-server:latest
          docker pull my-app-client:latest
          docker-compose up -d  # This assumes a docker-compose.yml is present on the server